import type {
  AppOverview,
  RuntimeOverview,
  SfxStudioOverview,
  TtsStudioOverview,
  VoiceLabOverview,
} from "./types";

export const fallbackOverview: AppOverview = {
  productName: "SoundWorks",
  architecture: {
    layers: [
      {
        id: "react-ui",
        name: "React UI",
        responsibility:
          "Workflow surfaces, library navigation, waveform review, and composition controls.",
        status: "scaffolded",
      },
      {
        id: "tauri-commands",
        name: "Tauri Commands",
        responsibility:
          "Narrow command bridge between the UI and local Rust services.",
        status: "scaffolded",
      },
      {
        id: "soundworks-core",
        name: "Rust Core",
        responsibility:
          "Shared domain contracts for assets, recipes, jobs, providers, and exports.",
        status: "scaffolded",
      },
      {
        id: "worker-runtime",
        name: "Worker Runtime",
        responsibility:
          "Model execution, installation, device capabilities, progress, and cancellation.",
        status: "scaffolded",
      },
    ],
  },
  studios: [
    {
      id: "tts",
      name: "TTS Studio",
      route: "/studios/tts",
      status: "scaffolded",
    },
    {
      id: "voice-lab",
      name: "Voice Lab",
      route: "/studios/voice-lab",
      status: "scaffolded",
    },
    {
      id: "sfx",
      name: "SFX + Ambience",
      route: "/studios/sfx",
      status: "scaffolded",
    },
    {
      id: "loops",
      name: "Samples + Loops",
      route: "/studios/loops",
      status: "planned",
    },
    {
      id: "songs",
      name: "Song Studio",
      route: "/studios/songs",
      status: "planned",
    },
    {
      id: "video-to-audio",
      name: "Video to Audio",
      route: "/studios/video-to-audio",
      status: "planned",
    },
  ],
  commands: [
    {
      name: "get_app_overview",
      direction: "ui-to-backend",
      purpose:
        "Load scaffolded architecture and workflow metadata from the Rust backend.",
    },
    {
      name: "get_provider_catalog",
      direction: "ui-to-backend",
      purpose:
        "Load provider/model manifests, capability defaults, and matching inputs.",
    },
    {
      name: "get_runtime_overview",
      direction: "ui-to-backend",
      purpose:
        "Report worker runtime policy, device/model state, job progress, and cancellation readiness.",
    },
    {
      name: "get_model_evaluation_catalog",
      direction: "ui-to-backend",
      purpose:
        "Load source-backed model scorecards, fixtures, recommendation status, and product eligibility gates.",
    },
    {
      name: "get_tts_studio_overview",
      direction: "ui-to-backend",
      purpose:
        "Load TTS script segmentation, voice consent gates, provider limits, submission preview, and saved voice-clip output.",
    },
    {
      name: "get_voice_lab_overview",
      direction: "ui-to-backend",
      purpose:
        "Load voice profile consent state, clone/fine-tune/conversion modes, provider scorecards, safety gates, and saved conversion output.",
    },
    {
      name: "get_sfx_studio_overview",
      direction: "ui-to-backend",
      purpose:
        "Load SFX and ambience prompts, capability-driven controls, variant previews, provider scorecards, loop checks, post-processing, and saved outputs.",
    },
  ],
  providerCatalog: {
    schemaVersion: 1,
    providerCount: 1,
    modelCount: 3,
    capabilityCount: 12,
    workflows: [
      {
        workflow: "tts",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-speech-suite",
      },
      {
        workflow: "voice-clone",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-speech-suite",
      },
      {
        workflow: "voice-conversion",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-speech-suite",
      },
      {
        workflow: "sfx",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-generation-suite",
      },
      {
        workflow: "ambience",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-generation-suite",
      },
      {
        workflow: "instrument-sample",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-generation-suite",
      },
      {
        workflow: "loop",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-generation-suite",
      },
      {
        workflow: "song",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-generation-suite",
      },
      {
        workflow: "stem-separation",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-utility-suite",
      },
      {
        workflow: "video-to-audio",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-generation-suite",
      },
      {
        workflow: "edit",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-utility-suite",
      },
      {
        workflow: "composition-render",
        defaultProviderId: "soundworks-reference",
        defaultModelId: "reference-utility-suite",
      },
    ],
  },
  modelEvaluation: {
    schemaVersion: 1,
    candidateCount: 28,
    sourceCount: 67,
    fixtureCount: 9,
    laneCount: 10,
    statusCounts: {
      "promising-spike": 24,
      blocked: 4,
    },
    productEligibilityCounts: {
      "product-candidate": 2,
      "needs-runtime-port": 7,
      "research-only": 15,
      blocked: 4,
    },
    recommendedCandidateIds: [
      "kokoro-82m",
      "chatterbox",
      "rvc",
      "moss-soundeffect",
      "ace-step-1-5",
      "mmaudio",
    ],
  },
  ttsStudio: {
    schemaVersion: 1,
    segmentCount: 3,
    speakerCount: 2,
    providerCount: 1,
    canSubmit: true,
    selectedProviderId: "soundworks-reference",
    selectedModelId: "reference-speech-suite",
    savedAssetKind: "voice-clip",
  },
  voiceLab: {
    schemaVersion: 1,
    modeCount: 3,
    profileCount: 2,
    providerCount: 8,
    safetyGateCount: 4,
    canSubmitConversion: true,
    selectedConversionCandidateId: "rvc",
    savedAssetKind: "voice-clip",
  },
  sfxStudio: {
    schemaVersion: 1,
    variantCount: 3,
    savedOutputCount: 2,
    providerCount: 2,
    scorecardCount: 9,
    canSubmit: true,
    selectedProviderId: "soundworks-reference",
    selectedModelId: "reference-generation-suite",
    savedAssetKinds: ["sfx", "ambience"],
  },
};

export const fallbackRuntime: RuntimeOverview = {
  schemaVersion: 1,
  packagingPolicy: {
    name: "SoundWorks shipped desktop runtime",
    productRuntimeAllowsPython: false,
    shippedPlatforms: ["mac-os", "windows"],
    workerProcess: "app-managed-sidecar",
    modelCacheRoots: [
      {
        platform: "mac-os",
        pathHint: "~/Library/Application Support/SoundWorks/models",
        purpose: "macOS packaged and user-installed model cache",
      },
      {
        platform: "windows",
        pathHint: "%APPDATA%\\SoundWorks\\models",
        purpose: "Windows packaged and user-installed model cache",
      },
    ],
  },
  devices: [
    {
      accelerator: "cpu",
      name: "Apple Silicon CPU",
      memoryMb: 32768,
      available: true,
    },
    {
      accelerator: "mps",
      name: "Apple Metal Performance Shaders",
      memoryMb: 32768,
      available: true,
      driver: "Metal",
    },
  ],
  statusCounts: {
    installed: 3,
    available: 0,
    unavailable: 0,
  },
  modelStates: [
    {
      providerId: "soundworks-reference",
      modelId: "reference-speech-suite",
      modelName: "Reference Speech Suite",
      availability: "installed",
      installStatus: "packaged",
      health: "ready",
      workflows: ["tts", "voice-clone", "voice-conversion"],
      reasons: [],
      cache: {
        status: "ready",
        expectedSizeMb: 2048,
        diskUsageMb: 2048,
        warmup: "cold",
      },
      compatibility: {
        supported: true,
        selectedAccelerator: "cpu",
        minMemoryMb: 4096,
        availableMemoryMb: 32768,
        requiresNetwork: false,
        reasons: [],
      },
    },
    {
      providerId: "soundworks-reference",
      modelId: "reference-generation-suite",
      modelName: "Reference Audio Generation Suite",
      availability: "installed",
      installStatus: "packaged",
      health: "ready",
      workflows: [
        "sfx",
        "ambience",
        "instrument-sample",
        "loop",
        "song",
        "video-to-audio",
      ],
      reasons: [],
      cache: {
        status: "ready",
        expectedSizeMb: 8192,
        diskUsageMb: 8192,
        warmup: "cold",
      },
      compatibility: {
        supported: true,
        selectedAccelerator: "cpu",
        minMemoryMb: 12288,
        availableMemoryMb: 32768,
        requiresNetwork: false,
        reasons: [],
      },
    },
    {
      providerId: "soundworks-reference",
      modelId: "reference-utility-suite",
      modelName: "Reference Utility Suite",
      availability: "installed",
      installStatus: "packaged",
      health: "ready",
      workflows: ["stem-separation", "edit", "composition-render"],
      reasons: [],
      cache: {
        status: "ready",
        expectedSizeMb: 1024,
        diskUsageMb: 1024,
        warmup: "cold",
      },
      compatibility: {
        supported: true,
        selectedAccelerator: "cpu",
        minMemoryMb: 2048,
        availableMemoryMb: 32768,
        requiresNetwork: false,
        reasons: [],
      },
    },
  ],
  jobs: [
    {
      id: "job-runtime-reference-generate",
      kind: "generate-audio",
      status: "running",
      providerId: "soundworks-reference",
      modelId: "reference-speech-suite",
      progress: {
        percent: 42,
        message: "Generating preview audio from queued worker contract.",
      },
      cancellation: "cancellable",
      retryCount: 0,
      logTail: [
        "claimed job from local queue",
        "loaded model package from cache",
        "streamed progress event 42%",
      ],
      actionableError: null,
    },
    {
      id: "job-runtime-reference-cache-repair",
      kind: "evaluate-model",
      status: "failed",
      providerId: "soundworks-reference",
      modelId: "reference-speech-suite",
      progress: {
        percent: 0,
        message: "Runtime validation detected a repairable package issue.",
      },
      cancellation: "not-cancellable",
      retryCount: 0,
      logTail: [
        "verified package manifest",
        "detected cache checksum mismatch",
      ],
      actionableError: {
        code: "runtime.cache_mismatch",
        summary: "Model package cache needs repair",
        recovery:
          "Reinstall the provider package or clear the model cache entry before retrying.",
      },
    },
  ],
  validationChecks: [
    {
      id: "runtime.platforms",
      status: "passed",
      summary: "Packaging policy targets macOS and Windows desktop builds.",
    },
    {
      id: "runtime.no_python",
      status: "passed",
      summary: "Product-enabled runtime manifests do not require Python.",
    },
    {
      id: "runtime.devices",
      status: "passed",
      summary: "Runtime device inventory can report available accelerators.",
    },
  ],
};

export const fallbackTtsStudio: TtsStudioOverview = {
  schemaVersion: 1,
  script: {
    id: "script-launch-read",
    title: "Launch read",
    language: "en-US",
    segments: [
      {
        id: "seg-001",
        position: 1,
        speakerLabel: "Narrator",
        text: "SoundWorks keeps the voice pass close to the edit.",
        sceneLabel: "Intro",
        targetDurationMs: 3100,
        regeneratePolicy: "keep-timing-with-neighbors",
      },
      {
        id: "seg-002",
        position: 2,
        speakerLabel: "Producer",
        text: "Try the warmer take, but keep the last phrase locked to picture.",
        sceneLabel: "Direction",
        targetDurationMs: 3900,
        regeneratePolicy: "regenerate-independently",
      },
      {
        id: "seg-003",
        position: 3,
        speakerLabel: "Narrator",
        text: "When it lands, save it as a project voice clip with the recipe attached.",
        sceneLabel: "Outro",
        targetDurationMs: 4300,
        regeneratePolicy: "keep-timing-with-neighbors",
      },
    ],
    pronunciationDictionary: [
      {
        term: "SoundWorks",
        pronunciation: "sound works",
        appliesToLanguage: "en-US",
      },
    ],
  },
  speakers: [
    {
      label: "Narrator",
      role: "Primary narration",
      voiceProfileId: "voice-profile-narrator",
      language: "en-US",
      consentRequired: true,
      consentStatus: "explicit-consent-recorded",
    },
    {
      label: "Producer",
      role: "Direction callout",
      voiceProfileId: "voice-profile-producer",
      language: "en-US",
      consentRequired: true,
      consentStatus: "explicit-consent-recorded",
    },
  ],
  voiceProfiles: [
    {
      id: "voice-profile-narrator",
      displayName: "Narrator consented profile",
      consent: "explicit-consent-recorded",
      allowedUses: ["tts", "project-only", "commercial"],
    },
    {
      id: "voice-profile-producer",
      displayName: "Producer consented profile",
      consent: "explicit-consent-recorded",
      allowedUses: ["tts", "project-only", "commercial"],
    },
  ],
  providerOptions: [
    {
      providerId: "soundworks-reference",
      modelId: "reference-speech-suite",
      modelVersion: "0.1.0",
      displayName:
        "SoundWorks Reference Capability Registry / Reference Speech Suite",
      runtime: "local",
      installStatus: "packaged",
      runnable: true,
      outputFormat: "wav",
      sampleRateHz: 48000,
      channelLayout: "mono",
      supportedLanguages: [],
      maxSpeakers: null,
      maxDurationMs: null,
      commercialUseAllowed: true,
      requiresVoiceConsent: true,
      watermark: "sidecar-only",
      limitations: ["Voice profile consent is required before generation."],
    },
  ],
  selectedProvider: {
    providerId: "soundworks-reference",
    modelId: "reference-speech-suite",
    modelVersion: "0.1.0",
    runtime: "local",
    accepted: true,
    blocker: "Voice profile consent is required before generation.",
  },
  controls: {
    speed: 1,
    style: "clear narration",
    emotion: "warm",
    targetLoudnessLufs: -18,
    normalizeOutput: true,
    preserveSegmentTiming: true,
    promoteToProjectLibrary: true,
  },
  generationPlan: {
    chunks: [
      {
        id: "chunk-seg-001",
        segmentIds: ["seg-001"],
        speakerLabel: "Narrator",
        voiceProfileId: "voice-profile-narrator",
        targetDurationMs: 3100,
        regeneratePolicy: "keep-timing-with-neighbors",
      },
      {
        id: "chunk-seg-002",
        segmentIds: ["seg-002"],
        speakerLabel: "Producer",
        voiceProfileId: "voice-profile-producer",
        targetDurationMs: 3900,
        regeneratePolicy: "regenerate-independently",
      },
      {
        id: "chunk-seg-003",
        segmentIds: ["seg-003"],
        speakerLabel: "Narrator",
        voiceProfileId: "voice-profile-narrator",
        targetDurationMs: 4300,
        regeneratePolicy: "keep-timing-with-neighbors",
      },
    ],
    stitching: {
      crossfadeMs: 35,
      preserveSegmentTiming: true,
      silenceTrim: true,
      normalizeLoudnessLufs: -18,
    },
    estimatedTotalDurationMs: 11300,
    preservesSpeakerConsistency: true,
  },
  submission: {
    canSubmit: true,
    job: {
      id: "job-tts-studio-reference",
      recipeId: "recipe-tts-studio-reference",
      kind: "generate-audio",
      status: "queued",
      progress: {
        percent: 0,
        message: "Ready to queue TTS generation.",
      },
      outputVersionIds: ["version-tts-studio-reference-a"],
      error: null,
    },
    recipe: {
      id: "recipe-tts-studio-reference",
      workflow: "tts",
      outputAssetIds: ["asset-tts-studio-reference"],
    },
    blockingReasons: [],
    warnings: [
      "Post-processing will normalize dialogue loudness after stitching.",
    ],
  },
  savedOutput: {
    asset: {
      id: "asset-tts-studio-reference",
      kind: "voice-clip",
      name: "TTS Studio narration draft",
      tags: ["voice-clips", "tts", "multi-speaker"],
      currentVersionId: "version-tts-studio-reference-a",
    },
    version: {
      id: "version-tts-studio-reference-a",
      file: {
        storagePath:
          "soundworks-library/projects/project-demo/voice-clips/asset-tts-studio-reference/version-tts-studio-reference-a/media.wav",
        format: "wav",
      },
      technical: {
        sampleRateHz: 48000,
        channels: 1,
        durationMs: 11300,
        loudnessLufs: -18,
      },
    },
    promotedToProjectLibrary: true,
    waveformPreviewReady: true,
  },
  validationChecks: [
    {
      id: "tts.script_segments",
      status: "passed",
      summary:
        "Script is segmented by speaker and scene for per-segment regeneration.",
    },
    {
      id: "tts.consent_gate",
      status: "passed",
      summary:
        "Voice-clone capable generation requires explicit consent before submission.",
    },
    {
      id: "tts.asset_promotion",
      status: "passed",
      summary:
        "Successful output is represented as a project Voice clip with recipe provenance.",
    },
  ],
};

export const fallbackVoiceLab: VoiceLabOverview = {
  schemaVersion: 1,
  modes: [
    {
      mode: "zero-shot-clone",
      label: "Zero-shot clone",
      workflow: "voice-clone",
      inputAssetKinds: ["reference-audio"],
      outputAssetKind: "voice-clip",
      providerCandidateIds: [
        "chatterbox",
        "gpt-sovits",
        "f5-tts",
        "cosyvoice-2",
        "openvoice-v2",
        "xtts-v2",
      ],
      ready: true,
    },
    {
      mode: "few-shot-fine-tune",
      label: "Few-shot fine-tune",
      workflow: "voice-clone",
      inputAssetKinds: ["reference-audio"],
      outputAssetKind: "voice-clip",
      providerCandidateIds: ["gpt-sovits", "f5-tts", "cosyvoice-2"],
      ready: true,
    },
    {
      mode: "voice-conversion",
      label: "Voice conversion",
      workflow: "voice-conversion",
      inputAssetKinds: ["reference-audio", "voice-clip"],
      outputAssetKind: "voice-clip",
      providerCandidateIds: ["chatterbox", "openvoice-v2", "rvc"],
      ready: true,
    },
  ],
  voiceProfiles: [
    {
      profile: {
        id: "voice-profile-narrator",
        displayName: "Narrator consented profile",
        consent: "explicit-consent-recorded",
        allowedUses: [
          "tts",
          "voice-conversion",
          "fine-tuning",
          "project-only",
          "commercial",
        ],
      },
      speakerIdentity: "Narrator",
      language: "en-US",
      sourceClipIds: [
        "voice-ref-narrator-close",
        "voice-ref-narrator-energetic",
      ],
      modeReadiness: [
        { mode: "zero-shot-clone", ready: true, reason: null },
        { mode: "few-shot-fine-tune", ready: true, reason: null },
        { mode: "voice-conversion", ready: true, reason: null },
      ],
      commercialUseAllowed: true,
      safetySummary:
        "Explicit consent covers TTS, fine-tuning, and conversion for this project.",
    },
    {
      profile: {
        id: "voice-profile-archival",
        displayName: "Archival interview review",
        consent: "requires-review",
        allowedUses: ["project-only"],
      },
      speakerIdentity: "Interview guest",
      language: "en-US",
      sourceClipIds: ["voice-ref-archival-interview"],
      modeReadiness: [
        {
          mode: "zero-shot-clone",
          ready: false,
          reason: "Explicit voice consent has not been recorded.",
        },
        {
          mode: "few-shot-fine-tune",
          ready: false,
          reason: "Fine-tuning requires explicit consent and ownership notes.",
        },
        {
          mode: "voice-conversion",
          ready: false,
          reason: "Conversion is disabled until consent review passes.",
        },
      ],
      commercialUseAllowed: false,
      safetySummary:
        "Kept visible for review, but all cloning and conversion actions are gated.",
    },
  ],
  referenceClips: [
    {
      id: "voice-ref-narrator-close",
      assetId: "asset-narrator-close-ref",
      profileId: "voice-profile-narrator",
      label: "Close mic neutral read",
      durationMs: 18200,
      consent: "explicit-consent-recorded",
      ownerAttestation: "speaker-signed",
      acceptedForModes: [
        "zero-shot-clone",
        "few-shot-fine-tune",
        "voice-conversion",
      ],
    },
    {
      id: "voice-ref-narrator-energetic",
      assetId: "asset-narrator-energy-ref",
      profileId: "voice-profile-narrator",
      label: "Energetic promo read",
      durationMs: 24600,
      consent: "explicit-consent-recorded",
      ownerAttestation: "speaker-signed",
      acceptedForModes: ["few-shot-fine-tune"],
    },
    {
      id: "voice-ref-archival-interview",
      assetId: "asset-archival-interview-ref",
      profileId: "voice-profile-archival",
      label: "Interview excerpt",
      durationMs: 31400,
      consent: "requires-review",
      ownerAttestation: "review-required",
      acceptedForModes: [],
    },
  ],
  conversionSource: {
    assetId: "asset-voice-lab-source-read",
    name: "Producer dry read",
    durationMs: 7800,
    kind: "reference-audio",
  },
  providerScorecards: [
    {
      candidateId: "chatterbox",
      name: "Chatterbox",
      provider: "Resemble AI",
      lanes: ["tts", "voice-clone", "voice-conversion"],
      status: "promising-spike",
      productEligibility: "needs-runtime-port",
      readiness: "needs-runtime-port",
      runtimePath: "external-executable",
      commercialUse: "allowed",
      recommended: true,
      blockers: ["Need no-Python product path and watermark/provenance validation"],
      notes: "Strong voice candidate for a packaged provider spike.",
    },
    {
      candidateId: "chatterbox-turbo",
      name: "Chatterbox Turbo",
      provider: "Resemble AI",
      lanes: ["tts"],
      status: "promising-spike",
      productEligibility: "needs-runtime-port",
      readiness: "unsuitable",
      runtimePath: "external-executable",
      commercialUse: "allowed",
      recommended: false,
      blockers: [
        "Need SoundWorks-owned realtime latency measurements",
        "Candidate is tracked for TTS only and is not a Voice Lab provider.",
      ],
      notes: "Track separately from base Chatterbox because latency is the product question.",
    },
    {
      candidateId: "gpt-sovits",
      name: "GPT-SoVITS",
      provider: "RVC-Boss",
      lanes: ["tts", "voice-clone"],
      status: "promising-spike",
      productEligibility: "research-only",
      readiness: "research-only",
      runtimePath: "python-poc-only",
      commercialUse: "unknown",
      recommended: false,
      blockers: ["No product-safe no-Python runtime path yet"],
      notes: "Useful zero/few-shot voice baseline; research-only until isolated runtime strategy exists.",
    },
    {
      candidateId: "f5-tts",
      name: "F5-TTS",
      provider: "SWivid",
      lanes: ["tts", "voice-clone"],
      status: "blocked",
      productEligibility: "blocked",
      readiness: "blocked",
      runtimePath: "python-poc-only",
      commercialUse: "non-commercial",
      recommended: false,
      blockers: ["Pretrained model non-commercial license blocks product use"],
      notes: "Use only as a research comparison unless commercially trainable weights are produced.",
    },
    {
      candidateId: "cosyvoice-2",
      name: "CosyVoice 2",
      provider: "FunAudioLLM / Alibaba",
      lanes: ["tts", "voice-clone"],
      status: "promising-spike",
      productEligibility: "research-only",
      readiness: "research-only",
      runtimePath: "python-poc-only",
      commercialUse: "unknown",
      recommended: false,
      blockers: ["License and packaged runtime path unresolved"],
      notes: "Evaluate for quality and streaming behavior, not as first product provider.",
    },
    {
      candidateId: "openvoice-v2",
      name: "OpenVoice V2",
      provider: "MyShell AI",
      lanes: ["voice-clone", "voice-conversion", "tts"],
      status: "promising-spike",
      productEligibility: "needs-runtime-port",
      readiness: "needs-runtime-port",
      runtimePath: "external-executable",
      commercialUse: "allowed",
      recommended: false,
      blockers: ["Need consent UX and executable packaging proof"],
      notes: "Good voice-clone/conversion candidate once consent and packaging are in place.",
    },
    {
      candidateId: "rvc",
      name: "RVC",
      provider: "RVC Project",
      lanes: ["voice-conversion"],
      status: "promising-spike",
      productEligibility: "needs-runtime-port",
      readiness: "needs-runtime-port",
      runtimePath: "external-executable",
      commercialUse: "allowed",
      recommended: true,
      blockers: ["Must be routed only as voice conversion and gated by consent"],
      notes: "Score as speech-to-speech voice conversion, not text-to-speech.",
    },
    {
      candidateId: "xtts-v2",
      name: "XTTS-v2",
      provider: "Coqui",
      lanes: ["tts", "voice-clone"],
      status: "blocked",
      productEligibility: "blocked",
      readiness: "blocked",
      runtimePath: "python-poc-only",
      commercialUse: "non-commercial",
      recommended: false,
      blockers: [
        "Non-commercial model license blocks shipped product use",
        "Reference clip requirement must be normalized as 6 seconds from the model card unless docs are reconciled",
      ],
      notes: "Keep as a comparison/reference only unless licensing changes.",
    },
  ],
  selectedConversion: {
    canSubmit: true,
    job: {
      id: "job-voice-lab-conversion-reference",
      recipeId: "recipe-voice-lab-conversion-reference",
      kind: "generate-audio",
      status: "queued",
      outputVersionIds: ["version-voice-lab-conversion-reference-a"],
      error: null,
    },
    recipe: {
      id: "recipe-voice-lab-conversion-reference",
      workflow: "voice-conversion",
      provider: {
        providerId: "rvc",
        modelId: "rvc",
        runtime: "local",
      },
      request: {
        kind: "voiceConversion",
        sourceAudioAssetId: "asset-voice-lab-source-read",
        targetVoiceProfileId: "voice-profile-narrator",
        preserveTiming: true,
      },
      outputAssetIds: ["asset-voice-lab-conversion-reference"],
    },
    blockingReasons: [],
    warnings: [
      "RVC is represented as a gated provider spike until a packaged runtime port exists.",
      "Converted output keeps the source timing and is saved as a Voice clip with recipe provenance.",
    ],
  },
  savedOutput: {
    asset: {
      id: "asset-voice-lab-conversion-reference",
      kind: "voice-clip",
      name: "Narrator converted read",
      tags: ["voice-clips", "voice-conversion", "speech-to-speech"],
      currentVersionId: "version-voice-lab-conversion-reference-a",
    },
    version: {
      id: "version-voice-lab-conversion-reference-a",
      file: {
        storagePath:
          "soundworks-library/projects/project-demo/voice-clips/asset-voice-lab-conversion-reference/version-voice-lab-conversion-reference-a/media.wav",
        format: "wav",
      },
      technical: {
        sampleRateHz: 48000,
        channels: 1,
        durationMs: 7800,
        loudnessLufs: -18,
      },
    },
    waveformPreviewReady: true,
  },
  safetyGates: [
    {
      id: "voice.consent.explicit",
      status: "passed",
      summary:
        "Clone, fine-tune, and conversion modes require explicit voice consent.",
    },
    {
      id: "voice.unauthorized_clone.blocked",
      status: "passed",
      summary:
        "Profiles marked Requires review cannot queue cloning or conversion jobs.",
    },
    {
      id: "voice.conversion.source_audio",
      status: "passed",
      summary:
        "RVC-style conversion requires source audio and a target voice profile.",
    },
    {
      id: "voice.commercial_use.review",
      status: "warning",
      summary:
        "Noncommercial or unknown provider licenses stay visible as blocked/research-only scorecards.",
    },
  ],
  qaChecks: [
    {
      id: "qa.similarity",
      label: "Speaker similarity",
      status: "ready",
      target: "Compare converted output against the consented target profile.",
    },
    {
      id: "qa.intelligibility",
      label: "Intelligibility",
      status: "ready",
      target: "Confirm speech remains clear after conversion.",
    },
    {
      id: "qa.artifacts",
      label: "Artifacts",
      status: "needs-review",
      target: "Review pitch tracking, breaths, and metallic artifacts before export.",
    },
  ],
};

export const fallbackSfxStudio: SfxStudioOverview = {
  schemaVersion: 1,
  prompt: {
    id: "prompt-sfx-hatch-ambience",
    text: "Close metallic hatch impact with a short pressurized tail, followed by a low engine-room ambience bed.",
    negativePrompt: "music, dialogue, melody, crowd",
    category: "foley-impact",
    tags: ["foley", "metal", "engine-room"],
    referenceAudioAssetId: "asset-reference-metal-room-tone",
  },
  controls: {
    durationMs: 8000,
    variationCount: 3,
    intensity: 72,
    realism: 64,
    loopable: true,
    trimSilence: true,
    normalizeLoudnessLufs: -20,
    fadeInMs: 20,
    fadeOutMs: 140,
    loopCrossfadeMs: 180,
    promoteToProjectLibrary: true,
  },
  categoryPresets: [
    {
      category: "foley-impact",
      label: "Foley impact",
      defaultDurationMs: 1800,
      loopableDefault: false,
      outputKind: "sfx",
    },
    {
      category: "ambience-bed",
      label: "Ambience bed",
      defaultDurationMs: 12000,
      loopableDefault: true,
      outputKind: "ambience",
    },
    {
      category: "transition",
      label: "Transition",
      defaultDurationMs: 2400,
      loopableDefault: false,
      outputKind: "sfx",
    },
    {
      category: "ui-sound",
      label: "UI sound",
      defaultDurationMs: 900,
      loopableDefault: false,
      outputKind: "sfx",
    },
  ],
  providerOptions: [
    {
      providerId: "soundworks-reference",
      modelId: "reference-generation-suite",
      modelVersion: "0.1.0",
      displayName:
        "SoundWorks Reference Capability Registry / Reference Audio Generation Suite",
      workflow: "sfx",
      runtime: "local",
      installStatus: "packaged",
      runnable: true,
      outputAssetKind: "sfx",
      outputFormat: "wav",
      sampleRateHz: 48000,
      channelLayout: "stereo",
      minDurationMs: null,
      maxDurationMs: null,
      supportsReferenceAudio: false,
      supportsLooping: false,
      commercialUseAllowed: true,
      watermark: "sidecar-only",
      supportedControls: [
        "prompt",
        "category",
        "variation-count",
        "intensity",
        "realism",
        "batch-generation",
        "duration",
      ],
      limitations: [],
    },
    {
      providerId: "soundworks-reference",
      modelId: "reference-generation-suite",
      modelVersion: "0.1.0",
      displayName:
        "SoundWorks Reference Capability Registry / Reference Audio Generation Suite",
      workflow: "ambience",
      runtime: "local",
      installStatus: "packaged",
      runnable: true,
      outputAssetKind: "ambience",
      outputFormat: "wav",
      sampleRateHz: 48000,
      channelLayout: "stereo",
      minDurationMs: null,
      maxDurationMs: null,
      supportsReferenceAudio: false,
      supportsLooping: true,
      commercialUseAllowed: true,
      watermark: "sidecar-only",
      supportedControls: [
        "prompt",
        "category",
        "variation-count",
        "intensity",
        "realism",
        "batch-generation",
        "duration",
        "loopable",
      ],
      limitations: [],
    },
  ],
  selectedProvider: {
    providerId: "soundworks-reference",
    modelId: "reference-generation-suite",
    modelVersion: "0.1.0",
    workflow: "sfx",
    runtime: "local",
    accepted: true,
    blocker: null,
  },
  providerScorecards: [
    {
      candidateId: "moss-soundeffect",
      name: "MOSS-SoundEffect",
      provider: "OpenMOSS",
      lanes: ["sfx", "ambience"],
      status: "promising-spike",
      productEligibility: "product-candidate",
      readiness: "ready",
      runtimePath: "native-library-binding",
      commercialUse: "allowed",
      recommended: true,
      blockers: [
        "Need SoundWorks-owned prompt adherence smoke test and Windows packaging answer",
      ],
      notes:
        "Best first SFX spike because an Apache-licensed MLX path exists for local Mac validation.",
    },
    {
      candidateId: "stable-audio-3",
      name: "Stable Audio 3",
      provider: "Stability AI",
      lanes: ["song", "sfx", "ambience"],
      status: "promising-spike",
      productEligibility: "needs-runtime-port",
      readiness: "needs-runtime-port",
      runtimePath: "external-executable",
      commercialUse: "provider-terms",
      recommended: false,
      blockers: [
        "Community license and enterprise threshold must be enforced before product enablement",
      ],
      notes:
        "Strong broad audio candidate, but SoundWorks needs runnable Mac/Windows packaging proof and license gating.",
    },
    {
      candidateId: "stable-audio-open-1",
      name: "Stable Audio Open 1.0",
      provider: "Stability AI",
      lanes: ["sfx", "ambience", "loop"],
      status: "promising-spike",
      productEligibility: "needs-runtime-port",
      readiness: "needs-runtime-port",
      runtimePath: "external-executable",
      commercialUse: "provider-terms",
      recommended: false,
      blockers: ["Community license terms must be enforced"],
      notes:
        "SFX/music-bed candidate, but license terms make it less clean than Apache/MIT options.",
    },
    {
      candidateId: "audiocraft-audiogen",
      name: "AudioCraft / AudioGen",
      provider: "Meta",
      lanes: ["sfx"],
      status: "promising-spike",
      productEligibility: "research-only",
      readiness: "research-only",
      runtimePath: "python-poc-only",
      commercialUse: "unknown",
      recommended: false,
      blockers: [
        "Model card requires downstream risk investigation before product use",
      ],
      notes: "Baseline SFX comparator; not first product provider.",
    },
    {
      candidateId: "audioldm",
      name: "AudioLDM",
      provider: "AudioLDM authors",
      lanes: ["sfx", "ambience"],
      status: "blocked",
      productEligibility: "blocked",
      readiness: "blocked",
      runtimePath: "python-poc-only",
      commercialUse: "non-commercial",
      recommended: false,
      blockers: ["Non-commercial checkpoint license blocks product use"],
      notes: "Research comparison only.",
    },
    {
      candidateId: "audioldm-2",
      name: "AudioLDM 2",
      provider: "AudioLDM authors",
      lanes: ["sfx", "ambience"],
      status: "promising-spike",
      productEligibility: "research-only",
      readiness: "research-only",
      runtimePath: "python-poc-only",
      commercialUse: "unknown",
      recommended: false,
      blockers: ["License and no-Python runtime path unresolved"],
      notes: "Evaluate as SFX baseline only.",
    },
    {
      candidateId: "audiox",
      name: "AudioX",
      provider: "AudioX authors",
      lanes: ["sfx", "video-to-audio", "ambience"],
      status: "promising-spike",
      productEligibility: "research-only",
      readiness: "deferred-to-video-audio",
      runtimePath: "python-poc-only",
      commercialUse: "unknown",
      recommended: false,
      blockers: [
        "License, weights, and runtime packaging need validation",
        "Multimodal/video-to-audio workflow is tracked in sc-6183.",
      ],
      notes: "Good multimodal benchmark; not product-ready.",
    },
    {
      candidateId: "mmaudio",
      name: "MMAudio",
      provider: "MMAudio authors",
      lanes: ["video-to-audio", "sfx"],
      status: "promising-spike",
      productEligibility: "research-only",
      readiness: "deferred-to-video-audio",
      runtimePath: "python-poc-only",
      commercialUse: "unknown",
      recommended: true,
      blockers: [
        "Commercial rights and no-Python product path unresolved",
        "Multimodal/video-to-audio workflow is tracked in sc-6183.",
      ],
      notes: "Primary video-to-audio benchmark candidate.",
    },
    {
      candidateId: "thinksound",
      name: "ThinkSound",
      provider: "FunAudioLLM",
      lanes: ["video-to-audio", "sfx", "ambience"],
      status: "promising-spike",
      productEligibility: "research-only",
      readiness: "deferred-to-video-audio",
      runtimePath: "python-poc-only",
      commercialUse: "unknown",
      recommended: false,
      blockers: [
        "License and dependency footprint unresolved",
        "Multimodal/video-to-audio workflow is tracked in sc-6183.",
      ],
      notes: "Useful for reasoning-heavy video-to-audio comparisons.",
    },
  ],
  deferredMultimodalCandidateIds: ["audiox", "mmaudio", "thinksound"],
  variants: [
    {
      id: "sfx-variant-impact-tight",
      label: "Tight hatch impact",
      workflow: "sfx",
      assetKind: "sfx",
      category: "foley-impact",
      durationMs: 1800,
      loudnessLufs: -17.5,
      truePeakDbfs: -1,
      loopable: false,
      loopPoints: null,
      tags: ["engine-room", "foley", "impact", "metal", "tight"],
      selectedForSave: true,
    },
    {
      id: "sfx-variant-impact-heavy",
      label: "Heavy pressure hit",
      workflow: "sfx",
      assetKind: "sfx",
      category: "foley-impact",
      durationMs: 2400,
      loudnessLufs: -16,
      truePeakDbfs: -0.8,
      loopable: false,
      loopPoints: null,
      tags: ["engine-room", "foley", "heavy", "impact", "metal"],
      selectedForSave: false,
    },
    {
      id: "sfx-variant-engine-room-bed",
      label: "Engine room bed",
      workflow: "ambience",
      assetKind: "ambience",
      category: "ambience-bed",
      durationMs: 8000,
      loudnessLufs: -20,
      truePeakDbfs: -3,
      loopable: true,
      loopPoints: {
        startSample: 2400,
        endSample: 381600,
      },
      tags: ["ambience", "engine-room", "foley", "loopable", "metal"],
      selectedForSave: true,
    },
  ],
  comparison: {
    selectedVariantId: "sfx-variant-impact-tight",
    variantCount: 3,
    loopableVariantIds: ["sfx-variant-engine-room-bed"],
    savedVariantIds: ["sfx-variant-impact-tight", "sfx-variant-engine-room-bed"],
  },
  submission: {
    canSubmit: true,
    job: {
      id: "job-sfx-studio-reference",
      recipeId: "recipe-sfx-studio-reference",
      kind: "generate-audio",
      status: "queued",
      outputVersionIds: [
        "version-sfx-variant-impact-tight-a",
        "version-sfx-variant-engine-room-bed-a",
      ],
      error: null,
    },
    recipe: {
      id: "recipe-sfx-studio-reference",
      workflow: "sfx",
      outputAssetIds: [
        "asset-sfx-variant-impact-tight",
        "asset-sfx-variant-engine-room-bed",
      ],
    },
    blockingReasons: [],
    warnings: [
      "Reference audio is stored with the recipe but the selected provider treats it as context only.",
      "Loopability will be inspected with post-processing because the provider has no native loop control.",
      "Post-processing will trim leading and trailing silence.",
    ],
  },
  savedOutputs: [
    {
      variantId: "sfx-variant-impact-tight",
      asset: {
        id: "asset-sfx-variant-impact-tight",
        kind: "sfx",
        name: "Tight hatch impact",
        tags: ["engine-room", "foley", "impact", "metal", "tight"],
        currentVersionId: "version-sfx-variant-impact-tight-a",
      },
      version: {
        id: "version-sfx-variant-impact-tight-a",
        file: {
          storagePath:
            "soundworks-library/projects/project-demo/sfx/asset-sfx-variant-impact-tight/version-sfx-variant-impact-tight-a/media.wav",
          format: "wav",
        },
        technical: {
          sampleRateHz: 48000,
          channels: 1,
          durationMs: 1800,
          loudnessLufs: -17.5,
          loopPoints: null,
        },
      },
      exported: true,
      waveformPreviewReady: true,
    },
    {
      variantId: "sfx-variant-engine-room-bed",
      asset: {
        id: "asset-sfx-variant-engine-room-bed",
        kind: "ambience",
        name: "Engine room bed",
        tags: ["ambience", "engine-room", "foley", "loopable", "metal"],
        currentVersionId: "version-sfx-variant-engine-room-bed-a",
      },
      version: {
        id: "version-sfx-variant-engine-room-bed-a",
        file: {
          storagePath:
            "soundworks-library/projects/project-demo/ambience/asset-sfx-variant-engine-room-bed/version-sfx-variant-engine-room-bed-a/media.wav",
          format: "wav",
        },
        technical: {
          sampleRateHz: 48000,
          channels: 2,
          durationMs: 8000,
          loudnessLufs: -20,
          loopPoints: {
            startSample: 2400,
            endSample: 381600,
          },
        },
      },
      exported: true,
      waveformPreviewReady: true,
    },
  ],
  postProcessingActions: [
    {
      id: "trim-silence",
      operation: "trim",
      enabled: true,
      summary: "Trim leading and trailing silence before saving variants.",
    },
    {
      id: "normalize",
      operation: "normalize",
      enabled: true,
      summary: "Normalize selected variants for preview and export.",
    },
    {
      id: "fade-loop",
      operation: "fade",
      enabled: true,
      summary: "Apply fades and loop crossfade where loop points are present.",
    },
    {
      id: "convert-export",
      operation: "convert-format",
      enabled: true,
      summary: "Export WAV assets with metadata sidecars and recipe provenance.",
    },
  ],
  validationChecks: [
    {
      id: "sfx.provider_capabilities",
      status: "passed",
      summary:
        "Available controls are derived from SFX and ambience provider capabilities.",
    },
    {
      id: "sfx.variant_comparison",
      status: "passed",
      summary:
        "Multiple variants can be previewed, compared, selected, tagged, and saved.",
    },
    {
      id: "sfx.loop_points",
      status: "passed",
      summary: "Loopable ambience output includes inspectable loop points.",
    },
    {
      id: "sfx.multimodal_boundary",
      status: "passed",
      summary:
        "AudioX, MMAudio, and ThinkSound remain deferred to the video-to-audio story.",
    },
  ],
};
